### PR TITLE
Forgot the image :sweat:

### PR DESCRIPTION
**Pull request by glasnt**
Sorry @Mariatta :cry:

### CODE REVIEW

**Comment by Mariatta** [comment]
😳  My mistake for not catching it 😅 
Thanks!!

**Comment by glasnt** [comment]
Okay, I'm not sure why the image still isn't appearing on the website. I might have gotten the URL wrong? :sweat:

**Comment by Mariatta** [comment]
I'm looking into it!

**Comment by Mariatta** [comment]
Maybe the RTD build failed (happened before)

**Comment by glasnt** [comment]
How can we check, or force a rebuild?

**Comment by roadsideseb** [comment]
I just forced a rebuild and that seems to have fixed it 🤷‍♂️ 

@Mariatta I've added you as a maintainer as well, you should be able to do anything on that project now.

**Comment by Mariatta** [comment]
Yay! Thanks @elbaschid and @glasnt 🎉

**Comment by glasnt** [comment]
✨✨✨

Thanks @elbaschid!

**Pull request merged**
