### PR TITLE
Add how to RSVP

### PR DESCRIPTION
**Pull request by Mariatta**
Not sure if info@pycascades.com even exists but people need to know how to RSVP somehow :)

### CODE REVIEW

**Comment by Mariatta** [comment]
We talked about mentioning that there's a limit of 20-30 hikers. Any suggestion on how to phrase it? :)

**Comment by ericholscher** [comment]
Could also ticket this properly w/ tito (http://tito.io/) -- which is free for free events, and what we'll likely use for the conf, so prob worth getting it setup.

**Comment by Mariatta** [comment]
I'll see if I can set it up

**Comment by Mariatta** [comment]
This looks ok? 

screen shot 2017-05-03 at 5 07 40 pm

**Comment by roadsideseb** [comment]
We don't have info@pycascades.com for now but I can set that up. The RSVP through tito sounds even better though. Should we just link through to it?

It might be good to have a short description and maybe a link back to the website on tito as well.

Regarding the phrasing of the limit, I'd suggest something like:

> We want to be considerate of the trails and other people hiking there. We'll therefore limit the number of participants to X people so that others can enjoy the area alongside us.

Just my thoughts, I'm sure there's more eloquent ideas though.

**Comment by roadsideseb** [comment]
👍

**Pull request merged**
